version: "3"

services:
  plex:
    image: plexinc/pms-docker
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    restart: always
    environment:
      - "PLEX_CLAIM:${PLEX_CLAIM}"
      - "ADVERTISE_IP:${ADVERTISE_IP}"
    volumes:
      - "${CONFIG_PATH}:/config"
      - "${TRANSCODE_PATH}:/transcode"
      - "${DATA_PATH}:/data"
